addSbtPlugin("com.orrsella" % "sbt-stats" % "1.0.7")
addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")
addSbtPlugin("de.heikoseeberger" % "sbt-header" % "5.0.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.4")
